/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase5;

import clase3.Mascota;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class GatoApp extends javax.swing.JFrame {

    /**
     * Creates new form GatoApp
     */
    public GatoApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tCodigo = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        tEdad = new javax.swing.JTextField();
        cRaza = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tResultado = new javax.swing.JTextArea();
        bProcesar = new javax.swing.JButton();
        bComer = new javax.swing.JButton();
        bJugar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bTotal = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion para Registrar Datos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Introduzca los Datos del Gato");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Raza:");

        cRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angora", "Persa", "Siames", "Bengala", "DelMer" }));

        tResultado.setColumns(20);
        tResultado.setRows(5);
        jScrollPane1.setViewportView(tResultado);

        bProcesar.setMnemonic('p');
        bProcesar.setText("Procesar");
        bProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcesarActionPerformed(evt);
            }
        });

        bComer.setMnemonic('c');
        bComer.setText("Comer");
        bComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComerActionPerformed(evt);
            }
        });

        bJugar.setMnemonic('j');
        bJugar.setText("Jugar");
        bJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugarActionPerformed(evt);
            }
        });

        bSalir.setMnemonic('s');
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bTotal.setText("Total Gatos");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tNombre)
                                            .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bTotal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(bComer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(bLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProcesar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bComer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bJugar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSalir)
                    .addComponent(bTotal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcesarActionPerformed
       
       String codigo = tCodigo.getText();
       if(codigo.equals("")){
           JOptionPane.showMessageDialog(this, "El Codigo no puede estar VACIO",
                   "Error:", JOptionPane.ERROR_MESSAGE);
           tCodigo.requestFocus();
           return;           
       }
       
       for (Gato gato : gatos) {
            System.out.println(gato);            
        }
       
       int cod = 0;
       try {
           cod = Integer.parseInt(codigo);
       }catch (Exception e){
          JOptionPane.showMessageDialog(this, "El Codigo debe ser SOLO Numerico",
                   "Error:", JOptionPane.ERROR_MESSAGE);
          tCodigo.requestFocus();
          tCodigo.selectAll();
          return; 
       }
       
       String nombre = tNombre.getText().trim();
       if(nombre.equals("")){
           JOptionPane.showMessageDialog(this, "El Nombre no puede estar VACIO",
                   "Error:", JOptionPane.ERROR_MESSAGE);
           tNombre.requestFocus();
           return; 
       }
       
       String edad = tEdad.getText().trim();
       if(edad.equals("")){
           JOptionPane.showMessageDialog(this, "La Edad no puede estar VACIA",
                   "Error:", JOptionPane.ERROR_MESSAGE);
           tEdad.requestFocus();
           return; 
       }
       
       int ed = 0;
       try {
           ed = Integer.parseInt(edad);
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "La Edad debe ser SOLO Numerico",
                  "Error:", JOptionPane.ERROR_MESSAGE);
           tEdad.requestFocus();
           tEdad.selectAll();
          return; 
       }
       
//       String raza = cRaza.getSelectedItem().toString();
//       g = new Gato(nombre, ed, raza, cod);
//       tResultado.append(g.toString()); 
        gatos.add(new Gato(tNombre.getText(), Integer.parseInt(tEdad.getText()), cRaza.getSelectedItem().toString(), Integer.parseInt(tCodigo.getText())));
        tResultado.append(gatos.get(gatos.size()-1).toString() + "\n");        
             
    }//GEN-LAST:event_bProcesarActionPerformed

    private void bComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComerActionPerformed
//       if(g == null){
//           JOptionPane.showMessageDialog(this, "El Gato aun no fue instanciado",
//                  "Error:", JOptionPane.ERROR_MESSAGE);
//          return; 
//       }else{
//           tResultado.append("\n" + g.comer("Lasagna", 350.0f));
//       }
        if(gatos.size() < 1){
            JOptionPane.showMessageDialog(this, "El Gato aun no fue instanciado",
                  "Error:", JOptionPane.ERROR_MESSAGE);
            return; 
        }else{
           tResultado.append("\nGato " + gatos.get(gatos.size()-1).getNombre() + gatos.get(gatos.size()-1).comer("Lasagna", 350.0f));
        }
    }//GEN-LAST:event_bComerActionPerformed

    private void bJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugarActionPerformed
//        if(g == null){
//           JOptionPane.showMessageDialog(this, "El Gato aun no fue instanciado",
//                  "Error:", JOptionPane.ERROR_MESSAGE);
//          return; 
//       }else{
//           tResultado.append("\n" + g.jugar());
//       }
        if(gatos.size() < 1){
            JOptionPane.showMessageDialog(this, "El Gato aun no fue instanciado",
                  "Error:", JOptionPane.ERROR_MESSAGE);
            return; 
        }else{
           tResultado.append("\nGato " + gatos.get(gatos.size()-1).getNombre() + gatos.get(gatos.size()-1).jugar());
        }
    }//GEN-LAST:event_bJugarActionPerformed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
        tResultado.append("\nTotal Gatos: " + gatos.size());
    }//GEN-LAST:event_bTotalActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        tCodigo.setText("");
        tNombre.setText("");
        tEdad.setText("");
        tResultado.setText("");
        tCodigo.requestFocus();
    }//GEN-LAST:event_bLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GatoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GatoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GatoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GatoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GatoApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComer;
    private javax.swing.JButton bJugar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bProcesar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bTotal;
    private javax.swing.JComboBox<String> cRaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tEdad;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextArea tResultado;
    // End of variables declaration//GEN-END:variables
    private Gato g;
    ArrayList<Gato> gatos = new ArrayList<>();
}
