/*
 * To change this license header, choose License Headers in Pr    @Override
    public JFormattedTextField.AbstractFormatter getFormatter(JFormattedTextField tf) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
oject Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase13.Frames;

import clase8.Cliente;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emorel
 */
public class AppClientes extends javax.swing.JFrame {

    /**
     * Creates new form AppClientes
     */
    public AppClientes() {
        initComponents();
        loadClientesJtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fTxtRuc = new javax.swing.JFormattedTextField();
        fTxtDesc = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        bNuevo = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tClientes = new javax.swing.JTable();
        bCargar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejo de Archivos de Acceso Aleatorio - Registro de Clientes");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 51, 204)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Codigo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("RUC");

        txtCodigo.setEditable(false);
        txtCodigo.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Direccion");

        txtNombre.setEnabled(false);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtDireccion.setEnabled(false);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("%Desc");

        fTxtRuc.setFormatterFactory(new javax.swing.JFormattedTextField.AbstractFormatterFactory() {
            public javax.swing.JFormattedTextField.AbstractFormatter
            getFormatter(javax.swing.JFormattedTextField tf){
                try{
                    return new javax.swing.text.MaskFormatter("#######-#");
                } catch(java.text.ParseException pe){
                    pe.printStackTrace();
                }
                return null;
            }
        });
        fTxtRuc.setEnabled(false);

        fTxtDesc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        fTxtDesc.setEnabled(false);
        fTxtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fTxtDescKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTxtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDireccion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fTxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTxtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 51, 204)));

        bNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase13/Images/newIcon.png"))); // NOI18N
        bNuevo.setMnemonic('n');
        bNuevo.setText("NUEVO");
        bNuevo.setToolTipText("Nuevo Cliente");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });

        bAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase13/Images/addIcon.png"))); // NOI18N
        bAgregar.setMnemonic('a');
        bAgregar.setText("AGREGAR");
        bAgregar.setToolTipText("Agregar Cliente");
        bAgregar.setEnabled(false);
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase13/Images/modIcon.png"))); // NOI18N
        bModificar.setMnemonic('m');
        bModificar.setText("MODIFICAR");
        bModificar.setToolTipText("Modificar Cliente");
        bModificar.setEnabled(false);
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase13/Images/delIcon.png"))); // NOI18N
        bEliminar.setMnemonic('e');
        bEliminar.setText("ELIMINAR");
        bEliminar.setToolTipText("Eliminar Cliente");
        bEliminar.setEnabled(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(bNuevo)
                .addGap(45, 45, 45)
                .addComponent(bAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bModificar)
                .addGap(46, 46, 46)
                .addComponent(bEliminar)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNuevo)
                    .addComponent(bAgregar)
                    .addComponent(bModificar)
                    .addComponent(bEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tClientes);

        bCargar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase13/Images/loadIcon.png"))); // NOI18N
        bCargar.setMnemonic('c');
        bCargar.setText("CARGAR CLIENTES");

        bSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase13/Images/exiIcon.png"))); // NOI18N
        bSalir.setMnemonic('s');
        bSalir.setText("SALIR");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCargar)
                    .addComponent(bSalir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        enableFields();
        cleanFields();
        bAgregar.setEnabled(true);
        txtCodigo.setText(Integer.toString(getNewCod()));
        txtNombre.requestFocus();        
    }//GEN-LAST:event_bNuevoActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (Character.isDigit(evt.getKeyChar())){
            evt.consume();
	}
        if (txtNombre.getText().length() >= 32 ){
            evt.consume(); 
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void fTxtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTxtDescKeyTyped
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
	}        
    }//GEN-LAST:event_fTxtDescKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        if (txtNombre.getText().length() >= 50 ){
            evt.consume(); 
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        //Validar
        if(validateFields()){
            //Agregar Cliente
            addCliente();
            //Limpia los Campos
            cleanFields();
            //Deshabilita los campos
            disableFields();
        }  
    }//GEN-LAST:event_bAgregarActionPerformed

    private void tClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tClientesMouseClicked
        int fila = tClientes.getSelectedRow();
        if(fila >= 0){
            Cliente cliente = clientes.get(fila);
            txtCodigo.setText(Integer.toString(cliente.getCodigo()));
            txtNombre.setText(cliente.getNombre());
            fTxtRuc.setText(cliente.getRuc());
            txtDireccion.setText(cliente.getDireccion());
            fTxtDesc.setText(Float.toString(cliente.getDescuento()));
            
            enableFields();
            bModificar.setEnabled(true);
            bEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_tClientesMouseClicked

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        Cliente cliente = new Cliente();
        Number descuento = (Number)fTxtDesc.getValue();
        cliente.setCodigo(Integer.parseInt(txtCodigo.getText()));
        cliente.setRuc(fTxtRuc.getText());
        cliente.setNombre(txtNombre.getText());
        cliente.setDireccion(txtDireccion.getText());
        cliente.setDescuento(descuento.floatValue());
        
        int fila = tClientes.getSelectedRow();
        if(fila >= 0){
            validateFields();    
            clientes.get(fila).setCodigo(cliente.getCodigo()); 
            clientes.get(fila).setNombre(cliente.getNombre());
            clientes.get(fila).setRuc(cliente.getRuc());
            clientes.get(fila).setDireccion(cliente.getDireccion());            
            clientes.get(fila).setDescuento(cliente.getDescuento());

            tClientes.setValueAt(cliente.getCodigo(), fila, 0);
            tClientes.setValueAt(cliente.getNombre(), fila, 1);
            tClientes.setValueAt(cliente.getRuc(), fila, 2);
            tClientes.setValueAt(cliente.getDireccion(), fila, 3);
            tClientes.setValueAt(cliente.getDescuento(), fila, 4);

            cleanFields();
            disableFields();
            bModificar.setEnabled(false);
            bEliminar.setEnabled(false);
        }        
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int row = tClientes.getSelectedRow();
        if(row >= 0){
            int option = JOptionPane.showConfirmDialog(this, "Está seguro de eliminar?", 
                    "Eliminar Cliente", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                clientes.remove(row);
                modelo.removeRow(row);
                cleanFields();
                disableFields();
                bModificar.setEnabled(false);
                bEliminar.setEnabled(false);                
            }
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCargar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bSalir;
    private javax.swing.JFormattedTextField fTxtDesc;
    private javax.swing.JFormattedTextField fTxtRuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tClientes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    private int cod = 0;
    DefaultTableModel modelo;
    private Vector<Cliente> clientes = new Vector();
    
    //Limpiar los Campos
    private void cleanFields(){
        txtCodigo.setText("");
        fTxtRuc.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        fTxtDesc.setText("");
    }
    
    //Deshabilitar Campos
    private void disableFields(){
        fTxtRuc.setEnabled(false);
        txtNombre.setEnabled(false);        
        txtDireccion.setEnabled(false);
        fTxtDesc.setEnabled(false);
        bAgregar.setEnabled(false);
    }
    
    //Habilitar Campos
    private void enableFields(){
        fTxtRuc.setEnabled(true);
        txtNombre.setEnabled(true);
        txtDireccion.setEnabled(true);
        fTxtDesc.setEnabled(true);
    }
    
    //Valida los Campos
    private boolean validateFields() {        
        //Validar RUC vacio
        if(fTxtRuc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo RUC no puede estar VACIO",
                    "Error:", JOptionPane.ERROR_MESSAGE);
            fTxtRuc.requestFocus();
            return false;           
        }
        //Validar Nombre vacio
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo NOMBRE no puede estar VACIO",
                    "Error:", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return false;           
        }
        //Validar Direccion vacia
        if(txtDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo DIRECCION no puede estar VACIO",
                    "Error:", JOptionPane.ERROR_MESSAGE);
            txtDireccion.requestFocus();
            return false;           
        }
        //Validar Descuento        
        if(fTxtDesc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo DESCUENTO no puede estar VACIO",
                    "Error:", JOptionPane.ERROR_MESSAGE);
            fTxtDesc.requestFocus();
            return false;           
        }
        Number value = (Number)fTxtDesc.getValue();
        if(value.floatValue()<0 || value.floatValue()>30){
            JOptionPane.showMessageDialog(this, "Campo DESCUENTO Fuera de Rango [0 - 30]%",
                    "Error:", JOptionPane.ERROR_MESSAGE);
            fTxtDesc.requestFocus();
            return false;
        }
        return true;
    }
    
    //Nuevo Codigo
    private int getNewCod(){
        cod++;        
        return cod;
    }
    
    //Cargar JTable
    private void loadClientesJtable() {
        modelo = new DefaultTableModel();
        String nombresCol[] = {"Codigo", "Nombre", "RUC", "Direccion", "Descuento"};
        modelo.setColumnIdentifiers(nombresCol);
        tClientes.setModel(modelo); 
        tClientes.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }
    
    //Agregar Cliente al Vector
    private void addCliente(){
        Cliente cliente = new Cliente(); 
        Number descuento = (Number)fTxtDesc.getValue();
        cliente.setCodigo(Integer.parseInt(txtCodigo.getText()));
        cliente.setRuc(fTxtRuc.getText());
        cliente.setNombre(txtNombre.getText());
        cliente.setDireccion(txtDireccion.getText());
        cliente.setDescuento(descuento.floatValue());        
        
        clientes.add(cliente);
        Object[] fila = { cliente.getCodigo(), cliente.getNombre(), cliente.getRuc(), 
            cliente.getDireccion(), cliente.getDescuento()};
        modelo.addRow(fila);
    }
}
