/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase9;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author emorel
 */
public class PracticaClase9 extends javax.swing.JFrame {

    /**
     * Creates new form PracticaClase9
     */
    public PracticaClase9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnPulsame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textField_1 = new javax.swing.JTextField();
        rdbtnOpcion_1 = new javax.swing.JRadioButton();
        rdbtnOpcion_2 = new javax.swing.JRadioButton();
        rdbtnOpcion_3 = new javax.swing.JRadioButton();
        lblEstasSobreLa = new javax.swing.JLabel();
        lblUstedEligio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaColores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaColores = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaHobbies = new javax.swing.JTextArea();
        toggleRojo = new javax.swing.JToggleButton();
        toggleVerde = new javax.swing.JToggleButton();
        toggleAzul = new javax.swing.JToggleButton();
        panelColor = new javax.swing.JPanel();
        sliderNumeros = new javax.swing.JSlider();
        textFieldSlider = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textField_2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textField_3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Listeners");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Pulsa el Boton");

        btnPulsame.setBackground(new java.awt.Color(63, 81, 180));
        btnPulsame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPulsame.setForeground(new java.awt.Color(255, 255, 255));
        btnPulsame.setText("PULSAME");
        btnPulsame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulsameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Elige una opción:");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fernando", "Alberto", "Arturo" }));
        comboBox.setSelectedIndex(-1);
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre elegido");

        textField_1.setEditable(false);

        buttonGroup1.add(rdbtnOpcion_1);
        rdbtnOpcion_1.setText("Opcion 1");
        rdbtnOpcion_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_1MouseExited(evt);
            }
        });

        buttonGroup1.add(rdbtnOpcion_2);
        rdbtnOpcion_2.setText("Opcion 2");
        rdbtnOpcion_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_2MouseExited(evt);
            }
        });

        buttonGroup1.add(rdbtnOpcion_3);
        rdbtnOpcion_3.setText("Opcion 3");
        rdbtnOpcion_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdbtnOpcion_3MouseExited(evt);
            }
        });

        lblEstasSobreLa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEstasSobreLa.setText("Estas sobre la ");

        lblUstedEligio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUstedEligio.setText("Usted eligió ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Elija los colores que más le gusta");

        listaColores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rojo", "Verde", "Azul", "Amarillo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaColoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaColores);

        textAreaColores.setColumns(20);
        textAreaColores.setRows(5);
        jScrollPane2.setViewportView(textAreaColores);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Elija sus hobbies");

        jCheckBox1.setText("Senderismo");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox2.setText("Caza");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        jCheckBox3.setText("Pezca");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });

        jCheckBox4.setText("Lectura");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });

        jCheckBox5.setText("Dibujo");
        jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox5ItemStateChanged(evt);
            }
        });

        textAreaHobbies.setColumns(20);
        textAreaHobbies.setRows(5);
        jScrollPane3.setViewportView(textAreaHobbies);

        toggleRojo.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup2.add(toggleRojo);
        toggleRojo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        toggleRojo.setForeground(new java.awt.Color(255, 255, 255));
        toggleRojo.setText("ROJO");
        toggleRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRojoActionPerformed(evt);
            }
        });

        toggleVerde.setBackground(new java.awt.Color(0, 255, 0));
        buttonGroup2.add(toggleVerde);
        toggleVerde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        toggleVerde.setForeground(new java.awt.Color(255, 255, 255));
        toggleVerde.setText("VERDE");
        toggleVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleVerdeActionPerformed(evt);
            }
        });

        toggleAzul.setBackground(new java.awt.Color(0, 0, 255));
        buttonGroup2.add(toggleAzul);
        toggleAzul.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        toggleAzul.setForeground(new java.awt.Color(255, 255, 255));
        toggleAzul.setText("AZUL");
        toggleAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAzulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        sliderNumeros.setMajorTickSpacing(2);
        sliderNumeros.setMaximum(200);
        sliderNumeros.setMinorTickSpacing(2);
        sliderNumeros.setPaintTicks(true);
        sliderNumeros.setSnapToTicks(true);
        sliderNumeros.setToolTipText("");
        sliderNumeros.setValue(2);
        sliderNumeros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderNumerosStateChanged(evt);
            }
        });

        textFieldSlider.setEditable(false);
        textFieldSlider.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Escribe el nombre de una Persona:");

        textField_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_2KeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(63, 81, 180));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AÑADIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Solo se puede escribir Digitos");

        textField_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Event Listeners");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox5)
                                            .addComponent(jCheckBox4)
                                            .addComponent(jCheckBox3)
                                            .addComponent(jCheckBox2)
                                            .addComponent(jCheckBox1))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(toggleRojo)
                                            .addComponent(toggleVerde)
                                            .addComponent(toggleAzul))
                                        .addGap(18, 18, 18)
                                        .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sliderNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(textFieldSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdbtnOpcion_1)
                            .addComponent(rdbtnOpcion_2)
                            .addComponent(rdbtnOpcion_3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUstedEligio)
                            .addComponent(lblEstasSobreLa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPulsame)
                            .addComponent(jLabel1))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(textField_1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textField_2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jButton1)
                    .addComponent(jLabel7)
                    .addComponent(textField_3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPulsame)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnOpcion_1)
                            .addComponent(lblEstasSobreLa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnOpcion_2)
                            .addComponent(lblUstedEligio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnOpcion_3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(toggleRojo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(toggleVerde)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(toggleAzul))
                        .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox5))
                        .addComponent(jScrollPane3)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPulsameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulsameActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "¡Me has pulsado!", "Mensaje",
                        JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_btnPulsameActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
        textField_1.setText(comboBox.getItemAt(comboBox.getSelectedIndex()));
    }//GEN-LAST:event_comboBoxActionPerformed
//RADIOBUTTON 1
    private void rdbtnOpcion_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_1MouseClicked
        // TODO add your handling code here:
        lblUstedEligio.setText("Usted eligió ");
        lblUstedEligio.setText(lblUstedEligio.getText()+rdbtnOpcion_1.getText());
    }//GEN-LAST:event_rdbtnOpcion_1MouseClicked

    private void rdbtnOpcion_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_1MouseEntered
        // TODO add your handling code here:
        lblEstasSobreLa.setText(lblEstasSobreLa.getText()+rdbtnOpcion_1.getText());
    }//GEN-LAST:event_rdbtnOpcion_1MouseEntered

    private void rdbtnOpcion_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_1MouseExited
        // TODO add your handling code here:
        lblEstasSobreLa.setText("Estas sobre la ");
    }//GEN-LAST:event_rdbtnOpcion_1MouseExited
//RADIOBUTTON 2
    private void rdbtnOpcion_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_2MouseClicked
        // TODO add your handling code here:
        lblUstedEligio.setText("Usted eligió ");
        lblUstedEligio.setText(lblUstedEligio.getText()+rdbtnOpcion_2.getText());
    }//GEN-LAST:event_rdbtnOpcion_2MouseClicked

    private void rdbtnOpcion_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_2MouseEntered
        // TODO add your handling code here:
        lblEstasSobreLa.setText(lblEstasSobreLa.getText()+rdbtnOpcion_2.getText());
    }//GEN-LAST:event_rdbtnOpcion_2MouseEntered

    private void rdbtnOpcion_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_2MouseExited
        // TODO add your handling code here:
        lblEstasSobreLa.setText("Estas sobre la ");
    }//GEN-LAST:event_rdbtnOpcion_2MouseExited
//RADIOBUTTON 3
    private void rdbtnOpcion_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_3MouseClicked
        // TODO add your handling code here:
        lblUstedEligio.setText("Usted eligió ");
        lblUstedEligio.setText(lblUstedEligio.getText()+rdbtnOpcion_3.getText());
    }//GEN-LAST:event_rdbtnOpcion_3MouseClicked

    private void rdbtnOpcion_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_3MouseEntered
        // TODO add your handling code here:
        lblEstasSobreLa.setText(lblEstasSobreLa.getText()+rdbtnOpcion_3.getText());
    }//GEN-LAST:event_rdbtnOpcion_3MouseEntered

    private void rdbtnOpcion_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnOpcion_3MouseExited
        // TODO add your handling code here:
        lblEstasSobreLa.setText("Estas sobre la ");
    }//GEN-LAST:event_rdbtnOpcion_3MouseExited

    private void listaColoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaColoresMouseClicked
        // TODO add your handling code here:
        textAreaColores.append(listaColores.getSelectedValue()+"\n");
    }//GEN-LAST:event_listaColoresMouseClicked

    private void toggleRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRojoActionPerformed
        // TODO add your handling code here:
        panelColor.setBackground(Color.red);
    }//GEN-LAST:event_toggleRojoActionPerformed

    private void toggleVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleVerdeActionPerformed
        // TODO add your handling code here:
        panelColor.setBackground(Color.green);
    }//GEN-LAST:event_toggleVerdeActionPerformed

    private void toggleAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAzulActionPerformed
        // TODO add your handling code here:
        panelColor.setBackground(Color.blue);
    }//GEN-LAST:event_toggleAzulActionPerformed

    private void sliderNumerosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderNumerosStateChanged
        // TODO add your handling code here:
        textFieldSlider.setText(Integer.toString(sliderNumeros.getValue()));
    }//GEN-LAST:event_sliderNumerosStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        comboBox.addItem(textField_2.getText());
	textField_2.setText("");
	JOptionPane.showMessageDialog(this, "Nombre Añadido", "Mensaje",
                        JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textField_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
	}
    }//GEN-LAST:event_textField_3KeyTyped

    private void textField_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_2KeyTyped
        // TODO add your handling code here:
        if (Character.isDigit(evt.getKeyChar())){
            evt.consume();
	}
    }//GEN-LAST:event_textField_2KeyTyped

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            textAreaHobbies.append(jCheckBox1.getText()+"\n");
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox2.isSelected()){
            textAreaHobbies.append(jCheckBox2.getText()+"\n");
        }
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            textAreaHobbies.append(jCheckBox3.getText()+"\n");
        }
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox4.isSelected()){
            textAreaHobbies.append(jCheckBox4.getText()+"\n");
        }
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox5ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox5.isSelected()){
            textAreaHobbies.append(jCheckBox5.getText()+"\n");
        }
    }//GEN-LAST:event_jCheckBox5ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticaClase9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticaClase9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticaClase9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticaClase9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticaClase9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPulsame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstasSobreLa;
    private javax.swing.JLabel lblUstedEligio;
    private javax.swing.JList<String> listaColores;
    private javax.swing.JPanel panelColor;
    private javax.swing.JRadioButton rdbtnOpcion_1;
    private javax.swing.JRadioButton rdbtnOpcion_2;
    private javax.swing.JRadioButton rdbtnOpcion_3;
    private javax.swing.JSlider sliderNumeros;
    private javax.swing.JTextArea textAreaColores;
    private javax.swing.JTextArea textAreaHobbies;
    private javax.swing.JTextField textFieldSlider;
    private javax.swing.JTextField textField_1;
    private javax.swing.JTextField textField_2;
    private javax.swing.JTextField textField_3;
    private javax.swing.JToggleButton toggleAzul;
    private javax.swing.JToggleButton toggleRojo;
    private javax.swing.JToggleButton toggleVerde;
    // End of variables declaration//GEN-END:variables
}
